In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset=load_iris()

In [4]:
df=sns.load_dataset('iris')

In [5]:
X=df.iloc[:,:-1]

In [6]:
y=dataset.target

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [9]:
X_train

sepal_length  sepal_width  petal_length  petal_width
60            5.0          2.0           3.5          1.0
116           6.5          3.0           5.5          1.8
144           6.7          3.3           5.7          2.5
119           6.0          2.2           5.0          1.5
108           6.7          2.5           5.8          1.8
..            ...          ...           ...          ...
9             4.9          3.1           1.5          0.1
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
117           7.7          3.8           6.7          2.2
47            4.6          3.2           1.4          0.2

[105 rows x 4 columns]

In [10]:
from sklearn.naive_bayes import GaussianNB

In [11]:
gnb=GaussianNB()

In [12]:
gnb.fit(X_train,y_train)

GaussianNB()

In [13]:
y_pred=gnb.predict(X_test)

In [14]:
from  sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
print(confusion_matrix(y_test,y_pred))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [16]:
accuracy_score(y_test,y_pred)

1.0

In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [18]:
#Practice

In [114]:
df=sns.load_dataset('tips')

In [115]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [116]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [117]:
df.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [118]:
df.sex.unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [119]:
df.sex.unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [120]:
from sklearn.preprocessing import LabelEncoder

In [121]:
a=LabelEncoder()

In [122]:
ans=a.fit_transform(df[['day']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [123]:
df_day=pd.DataFrame(data=ans,columns=['day'])

In [124]:
df_day

day
0      2
1      2
2      2
3      2
4      2
..   ...
239    1
240    1
241    1
242    1
243    3

[244 rows x 1 columns]

In [125]:
df['day']=df_day['day']

In [126]:
df

total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No    2  Dinner     2
1         10.34  1.66    Male     No    2  Dinner     3
2         21.01  3.50    Male     No    2  Dinner     3
3         23.68  3.31    Male     No    2  Dinner     2
4         24.59  3.61  Female     No    2  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
239       29.03  5.92    Male     No    1  Dinner     3
240       27.18  2.00  Female    Yes    1  Dinner     2
241       22.67  2.00    Male    Yes    1  Dinner     2
242       17.82  1.75    Male     No    1  Dinner     2
243       18.78  3.00  Female     No    3  Dinner     2

[244 rows x 7 columns]

In [127]:
ans=a.fit_transform(df[['sex']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [128]:
df_sex=pd.DataFrame(data=ans)

In [129]:
df['sex']=df_sex

In [130]:
df

total_bill   tip  sex smoker  day    time  size
0         16.99  1.01    0     No    2  Dinner     2
1         10.34  1.66    1     No    2  Dinner     3
2         21.01  3.50    1     No    2  Dinner     3
3         23.68  3.31    1     No    2  Dinner     2
4         24.59  3.61    0     No    2  Dinner     4
..          ...   ...  ...    ...  ...     ...   ...
239       29.03  5.92    1     No    1  Dinner     3
240       27.18  2.00    0    Yes    1  Dinner     2
241       22.67  2.00    1    Yes    1  Dinner     2
242       17.82  1.75    1     No    1  Dinner     2
243       18.78  3.00    0     No    3  Dinner     2

[244 rows x 7 columns]

In [131]:
ans=a.fit_transform(df[['smoker']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [132]:
df_smoker=pd.DataFrame(data=ans)

In [133]:
df['smoker']=df_smoker

In [134]:
df

total_bill   tip  sex  smoker  day    time  size
0         16.99  1.01    0       0    2  Dinner     2
1         10.34  1.66    1       0    2  Dinner     3
2         21.01  3.50    1       0    2  Dinner     3
3         23.68  3.31    1       0    2  Dinner     2
4         24.59  3.61    0       0    2  Dinner     4
..          ...   ...  ...     ...  ...     ...   ...
239       29.03  5.92    1       0    1  Dinner     3
240       27.18  2.00    0       1    1  Dinner     2
241       22.67  2.00    1       1    1  Dinner     2
242       17.82  1.75    1       0    1  Dinner     2
243       18.78  3.00    0       0    3  Dinner     2

[244 rows x 7 columns]

In [135]:
df.dtypes

total_bill     float64
tip            float64
sex              int64
smoker           int64
day              int64
time          category
size             int64
dtype: object

In [136]:
df['target']=df.time

In [137]:
df

total_bill   tip  sex  smoker  day    time  size  target
0         16.99  1.01    0       0    2  Dinner     2  Dinner
1         10.34  1.66    1       0    2  Dinner     3  Dinner
2         21.01  3.50    1       0    2  Dinner     3  Dinner
3         23.68  3.31    1       0    2  Dinner     2  Dinner
4         24.59  3.61    0       0    2  Dinner     4  Dinner
..          ...   ...  ...     ...  ...     ...   ...     ...
239       29.03  5.92    1       0    1  Dinner     3  Dinner
240       27.18  2.00    0       1    1  Dinner     2  Dinner
241       22.67  2.00    1       1    1  Dinner     2  Dinner
242       17.82  1.75    1       0    1  Dinner     2  Dinner
243       18.78  3.00    0       0    3  Dinner     2  Dinner

[244 rows x 8 columns]

In [138]:
df=df.drop(['time'],axis=1)

In [139]:
df

total_bill   tip  sex  smoker  day  size  target
0         16.99  1.01    0       0    2     2  Dinner
1         10.34  1.66    1       0    2     3  Dinner
2         21.01  3.50    1       0    2     3  Dinner
3         23.68  3.31    1       0    2     2  Dinner
4         24.59  3.61    0       0    2     4  Dinner
..          ...   ...  ...     ...  ...   ...     ...
239       29.03  5.92    1       0    1     3  Dinner
240       27.18  2.00    0       1    1     2  Dinner
241       22.67  2.00    1       1    1     2  Dinner
242       17.82  1.75    1       0    1     2  Dinner
243       18.78  3.00    0       0    3     2  Dinner

[244 rows x 7 columns]

In [140]:
X=df.iloc[:,:-1]

In [141]:
X

total_bill   tip  sex  smoker  day  size
0         16.99  1.01    0       0    2     2
1         10.34  1.66    1       0    2     3
2         21.01  3.50    1       0    2     3
3         23.68  3.31    1       0    2     2
4         24.59  3.61    0       0    2     4
..          ...   ...  ...     ...  ...   ...
239       29.03  5.92    1       0    1     3
240       27.18  2.00    0       1    1     2
241       22.67  2.00    1       1    1     2
242       17.82  1.75    1       0    1     2
243       18.78  3.00    0       0    3     2

[244 rows x 6 columns]

In [142]:
y=df['target']

In [143]:
y

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: target, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [144]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [145]:
X_train

total_bill   tip  sex  smoker  day  size
61        13.81  2.00    1       1    1     2
146       18.64  1.36    0       0    3     3
52        34.81  5.20    0       0    2     4
66        16.45  2.47    0       0    1     2
26        13.37  2.00    1       0    1     2
..          ...   ...  ...     ...  ...   ...
67         3.07  1.00    0       1    1     1
192       28.44  2.56    1       1    3     2
117       10.65  1.50    0       0    3     2
47        32.40  6.00    1       0    2     4
172        7.25  5.15    1       1    2     2

[170 rows x 6 columns]

In [146]:
from sklearn.naive_bayes import GaussianNB

In [147]:
gnb=GaussianNB()

In [148]:
gnb.fit(X_train,y_train)

GaussianNB()

In [149]:
y_pred=gnb.predict(X_test)

In [150]:
print(list(y_test))

['Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Lunch', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch', 'Lunch', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner']


In [151]:
accuracy_score(y_test,y_pred)

0.8918918918918919

In [152]:
print(confusion_matrix(y_test,y_pred))

[[53  3]
 [ 5 13]]


In [153]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      Dinner       0.91      0.95      0.93        56
       Lunch       0.81      0.72      0.76        18

    accuracy                           0.89        74
   macro avg       0.86      0.83      0.85        74
weighted avg       0.89      0.89      0.89        74

